apiVersion: v1
kind: Service
metadata:
  name     : mongo-prod
  namespace: infra
  labels:
    app: mongo-prod

spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-prod

